[versions]
kotlin = "2.2.21"
ktor = "3.3.0"
logback = "1.4.14"
kotest = "6.0.7"
spotless = "7.2.1"

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor"}
ktor-server-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor"}
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest"}
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotest = { id = "io.kotest", version.ref = "kotest" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
release = { id = "net.researchgate.release", version = "3.1.0" }

